import { NextResponse } from "next/server"

type Place = {
  id: string
  name: string
  lat: number
  lon: number
  photos: string[]
  popularity: number
  description: string
  wikipediaUrl?: string
  tags: string[]
  distance?: number
}

const CACHE_TTL_MS = 1000 * 60 * 30 // 30 minutes

let cache: { ts: number; data: Place[] } | null = null

const FAMOUS_DESTINATIONS: Omit<Place, "distance">[] = [
  // Major Cities & Metros - Lower scores for cities
  {
    id: "mumbai",
    name: "Mumbai",
    lat: 19.076,
    lon: 72.8777,
    photos: ["https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200"],
    popularity: 80,
    description: "India's financial capital and Bollywood hub, known for its vibrant culture and coastal beauty.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mumbai",
    tags: ["city", "metropolitan", "beach", "culture"],
  },
  {
    id: "delhi",
    name: "Delhi",
    lat: 28.6139,
    lon: 77.209,
    photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200"],
    popularity: 78,
    description: "India's capital, a blend of ancient history and modern development with iconic monuments.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Delhi",
    tags: ["city", "capital", "heritage", "history"],
  },
  {
    id: "bangalore",
    name: "Bangalore",
    lat: 12.9716,
    lon: 77.5946,
    photos: ["https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1200"],
    popularity: 72,
    description: "India's Silicon Valley with pleasant weather, gardens, and modern culture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bangalore",
    tags: ["city", "modern", "gardens", "culture"],
  },
  {
    id: "kolkata",
    name: "Kolkata",
    lat: 22.5726,
    lon: 88.3639,
    photos: ["https://images.unsplash.com/photo-1558431382-27e303142255?w=1200"],
    popularity: 75,
    description: "The City of Joy, known for its colonial architecture and cultural richness.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kolkata",
    tags: ["city", "heritage", "culture", "art"],
  },
  {
    id: "hyderabad",
    name: "Hyderabad",
    lat: 17.385,
    lon: 78.4867,
    photos: ["https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1200"],
    popularity: 74,
    description: "The City of Pearls, famous for its biryani, IT industry, and historical monuments.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Hyderabad",
    tags: ["city", "food", "heritage", "modern"],
  },
  {
    id: "chennai",
    name: "Chennai",
    lat: 13.0827,
    lon: 80.2707,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 73,
    description: "Gateway to South India, known for temples, beaches, and classical arts.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chennai",
    tags: ["city", "beach", "temple", "culture"],
  },
  {
    id: "pune",
    name: "Pune",
    lat: 18.5204,
    lon: 73.8567,
    photos: ["https://images.unsplash.com/photo-1595248227483-f4f5a2c9c2e3?w=1200"],
    popularity: 71,
    description: "The Oxford of the East, known for education, IT, and pleasant climate.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Pune",
    tags: ["city", "modern", "education", "culture"],
  },
  {
    id: "ahmedabad",
    name: "Ahmedabad",
    lat: 23.0225,
    lon: 72.5714,
    photos: ["https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=1200"],
    popularity: 70,
    description: "UNESCO World Heritage City, textile hub, and Gujarati culture center.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ahmedabad",
    tags: ["city", "heritage", "culture", "shopping"],
  },

  // Top Vacation Destinations - High scores 95-99
  {
    id: "goa",
    name: "Goa",
    lat: 15.2993,
    lon: 74.124,
    photos: ["https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200"],
    popularity: 99,
    description: "India's beach paradise with Portuguese heritage, nightlife, and water sports.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Goa",
    tags: ["beach", "vacation", "adventure", "nightlife"],
  },
  {
    id: "leh-ladakh",
    name: "Leh-Ladakh",
    lat: 34.1526,
    lon: 77.577,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 98,
    description: "High-altitude desert paradise with stunning landscapes and Buddhist monasteries.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ladakh",
    tags: ["mountains", "adventure", "nature", "spiritual"],
  },
  {
    id: "manali",
    name: "Manali",
    lat: 32.2432,
    lon: 77.1892,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 97,
    description: "Himalayan hill station perfect for adventure sports and mountain getaways.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Manali,_Himachal_Pradesh",
    tags: ["mountains", "adventure", "nature", "snow"],
  },
  {
    id: "kashmir",
    name: "Kashmir",
    lat: 34.0837,
    lon: 74.7973,
    photos: ["https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1200"],
    popularity: 97,
    description: "Paradise on Earth with stunning valleys, gardens, and houseboats.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kashmir",
    tags: ["mountains", "nature", "vacation", "scenic"],
  },
  {
    id: "andaman-nicobar",
    name: "Andaman & Nicobar Islands",
    lat: 11.7401,
    lon: 92.6586,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 96,
    description: "Tropical islands with pristine beaches, coral reefs, and marine life.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Andaman_and_Nicobar_Islands",
    tags: ["beach", "island", "adventure", "vacation"],
  },
  {
    id: "kerala-backwaters",
    name: "Kerala Backwaters",
    lat: 9.4981,
    lon: 76.3388,
    photos: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200"],
    popularity: 96,
    description: "Serene network of canals with houseboat cruises and lush greenery.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kerala_Backwaters",
    tags: ["nature", "vacation", "relaxation", "scenic"],
  },
  {
    id: "rishikesh",
    name: "Rishikesh",
    lat: 30.0869,
    lon: 78.2676,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 95,
    description: "Yoga capital of the world, adventure sports hub on the Ganges.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Rishikesh",
    tags: ["spiritual", "adventure", "nature", "yoga"],
  },
  {
    id: "shimla",
    name: "Shimla",
    lat: 31.1048,
    lon: 77.1734,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 95,
    description: "Colonial-era hill station, summer capital of British India.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Shimla",
    tags: ["mountains", "heritage", "vacation", "scenic"],
  },

  // Rajasthan - Heritage & Desert
  {
    id: "jaipur",
    name: "Jaipur",
    lat: 26.9124,
    lon: 75.7873,
    photos: ["https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200"],
    popularity: 94,
    description: "The Pink City, famous for its royal palaces, forts, and vibrant bazaars.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jaipur",
    tags: ["heritage", "royal", "culture", "desert"],
  },
  {
    id: "udaipur",
    name: "Udaipur",
    lat: 24.5854,
    lon: 73.7125,
    photos: ["https://images.unsplash.com/photo-1599661046289-e3189784641c?w=1200"],
    popularity: 93,
    description: "The City of Lakes, known for its romantic palaces and Rajasthani heritage.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Udaipur",
    tags: ["heritage", "romantic", "lakes", "palace"],
  },
  {
    id: "jaisalmer",
    name: "Jaisalmer",
    lat: 26.9157,
    lon: 70.9083,
    photos: ["https://images.unsplash.com/photo-1580836572829-d56024b4bbc8?w=1200"],
    popularity: 92,
    description: "The Golden City in the Thar Desert, known for its yellow sandstone architecture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jaisalmer",
    tags: ["desert", "heritage", "adventure", "fort"],
  },
  {
    id: "jodhpur",
    name: "Jodhpur",
    lat: 26.2389,
    lon: 73.0243,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 90,
    description: "The Blue City, famous for Mehrangarh Fort and desert landscapes.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jodhpur",
    tags: ["heritage", "fort", "desert", "culture"],
  },
  {
    id: "pushkar",
    name: "Pushkar",
    lat: 26.4899,
    lon: 74.5511,
    photos: ["https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=1200"],
    popularity: 88,
    description: "Sacred town with the only Brahma temple and famous camel fair.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Pushkar",
    tags: ["spiritual", "heritage", "culture", "festival"],
  },
  {
    id: "mount-abu",
    name: "Mount Abu",
    lat: 24.5926,
    lon: 72.7156,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 87,
    description: "Rajasthan's only hill station with Dilwara Jain temples.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mount_Abu",
    tags: ["mountains", "heritage", "temple", "nature"],
  },
  {
    id: "ranthambore",
    name: "Ranthambore",
    lat: 26.0173,
    lon: 76.5026,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 91,
    description: "Famous national park for tiger sightings and fort ruins.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ranthambore_National_Park",
    tags: ["wildlife", "adventure", "nature", "heritage"],
  },
  {
    id: "bikaner",
    name: "Bikaner",
    lat: 28.0229,
    lon: 73.3119,
    photos: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0648?w=1200"],
    popularity: 84,
    description: "Desert city known for Junagarh Fort and camel breeding farms.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bikaner",
    tags: ["desert", "heritage", "fort", "culture"],
  },
  {
    id: "ajmer",
    name: "Ajmer",
    lat: 26.4499,
    lon: 74.6399,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 82,
    description: "Pilgrimage center with the dargah of Moinuddin Chishti.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ajmer",
    tags: ["spiritual", "heritage", "culture"],
  },
  {
    id: "chittorgarh",
    name: "Chittorgarh",
    lat: 24.8887,
    lon: 74.6269,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 81,
    description: "Home to the largest fort in India with tales of Rajput valor.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chittorgarh",
    tags: ["heritage", "fort", "history"],
  },

  // Uttar Pradesh - Heritage
  {
    id: "agra",
    name: "Agra",
    lat: 27.1767,
    lon: 78.0081,
    photos: ["https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200"],
    popularity: 99,
    description: "Home to the Taj Mahal, one of the Seven Wonders of the World.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Agra",
    tags: ["heritage", "monument", "history", "iconic"],
  },
  {
    id: "varanasi",
    name: "Varanasi",
    lat: 25.3176,
    lon: 82.9739,
    photos: ["https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=1200"],
    popularity: 94,
    description: "The spiritual capital of India, one of the oldest living cities in the world.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Varanasi",
    tags: ["spiritual", "heritage", "river", "culture"],
  },
  {
    id: "lucknow",
    name: "Lucknow",
    lat: 26.8467,
    lon: 80.9462,
    photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200"],
    popularity: 80,
    description: "City of Nawabs, known for Mughlai cuisine and Awadhi culture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lucknow",
    tags: ["heritage", "food", "culture", "history"],
  },
  {
    id: "allahabad",
    name: "Prayagraj (Allahabad)",
    lat: 25.4358,
    lon: 81.8463,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 79,
    description: "Sangam of three rivers, host to Kumbh Mela.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Prayagraj",
    tags: ["spiritual", "river", "culture", "festival"],
  },
  {
    id: "mathura-vrindavan",
    name: "Mathura-Vrindavan",
    lat: 27.4924,
    lon: 77.6737,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 85,
    description: "Birthplace of Lord Krishna, major pilgrimage destination.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mathura",
    tags: ["spiritual", "temple", "culture", "heritage"],
  },
  {
    id: "ayodhya",
    name: "Ayodhya",
    lat: 26.7922,
    lon: 82.1998,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 83,
    description: "Ancient city believed to be birthplace of Lord Rama.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ayodhya",
    tags: ["spiritual", "heritage", "temple", "history"],
  },

  // Himachal Pradesh & Uttarakhand - Mountains & Nature
  {
    id: "shimla", // Already included above, but let's assume this is a specific view or aspect
    name: "Shimla",
    lat: 31.1048,
    lon: 77.1734,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 95,
    description: "Former summer capital of British India, charming hill station with colonial architecture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Shimla",
    tags: ["mountains", "heritage", "nature", "romantic"],
  },
  {
    id: "manali", // Already included above
    name: "Manali",
    lat: 32.2432,
    lon: 77.1892,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 97,
    description: "Himalayan hill station perfect for adventure sports and mountain getaways.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Manali,_Himachal_Pradesh",
    tags: ["mountains", "adventure", "nature", "snow"],
  },
  {
    id: "dharamshala",
    name: "Dharamshala",
    lat: 32.219,
    lon: 76.3234,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 93,
    description: "Home to Dalai Lama and Tibetan government in exile.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Dharamshala",
    tags: ["mountains", "spiritual", "culture", "nature"],
  },
  {
    id: "kasol",
    name: "Kasol",
    lat: 32.0102,
    lon: 77.3152,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 90,
    description: "Mini Israel of India, backpacker's paradise in Parvati Valley.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kasol",
    tags: ["mountains", "adventure", "nature", "backpacking"],
  },
  {
    id: "spiti-valley",
    name: "Spiti Valley",
    lat: 32.2468,
    lon: 78.0338,
    photos: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200"],
    popularity: 92,
    description: "Cold desert mountain valley with Buddhist monasteries.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Spiti_Valley",
    tags: ["mountains", "adventure", "spiritual", "nature"],
  },
  {
    id: "dalhousie",
    name: "Dalhousie",
    lat: 32.5441,
    lon: 75.9471,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 86,
    description: "Hill station with colonial charm and panoramic valley views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Dalhousie,_Himachal_Pradesh",
    tags: ["mountains", "romantic", "nature", "heritage"],
  },
  {
    id: "rishikesh", // Already included above
    name: "Rishikesh",
    lat: 30.0869,
    lon: 78.2676,
    photos: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200"],
    popularity: 95,
    description: "Yoga capital of the world, adventure sports hub, and spiritual gateway to Himalayas.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Rishikesh",
    tags: ["spiritual", "adventure", "nature", "yoga"],
  },
  {
    id: "haridwar",
    name: "Haridwar",
    lat: 29.9457,
    lon: 78.1642,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 88,
    description: "Gateway to Char Dham, famous for Ganga Aarti.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Haridwar",
    tags: ["spiritual", "river", "culture", "heritage"],
  },
  {
    id: "mussoorie",
    name: "Mussoorie",
    lat: 30.4598,
    lon: 78.0644,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 89,
    description: "Queen of Hills with colonial architecture and mountain views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mussoorie",
    tags: ["mountains", "romantic", "nature", "heritage"],
  },
  {
    id: "nainital",
    name: "Nainital",
    lat: 29.3803,
    lon: 79.4636,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 87,
    description: "Lake district of India with scenic Himalayan views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Nainital",
    tags: ["mountains", "lakes", "nature", "romantic"],
  },
  {
    id: "auli",
    name: "Auli",
    lat: 30.5289,
    lon: 79.5769,
    photos: ["https://images.unsplash.com/photo-1551582045-6ec9c11d8697?w=1200"],
    popularity: 91,
    description: "Premier skiing destination in India with snow-covered slopes.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Auli",
    tags: ["mountains", "adventure", "snow", "skiing"],
  },
  {
    id: "kedarnath",
    name: "Kedarnath",
    lat: 30.7346,
    lon: 79.0669,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 89,
    description: "Sacred Hindu temple in the Himalayas, part of Char Dham.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kedarnath",
    tags: ["spiritual", "mountains", "temple", "pilgrimage"],
  },
  {
    id: "badrinath",
    name: "Badrinath",
    lat: 30.7433,
    lon: 79.4938,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 88,
    description: "One of the Char Dham pilgrimage sites in Uttarakhand.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Badrinath",
    tags: ["spiritual", "mountains", "temple", "pilgrimage"],
  },
  {
    id: "jim-corbett",
    name: "Jim Corbett National Park",
    lat: 29.5308,
    lon: 78.7716,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 90,
    description: "India's oldest national park, famous for Bengal tigers.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jim_Corbett_National_Park",
    tags: ["wildlife", "adventure", "nature"],
  },

  // Jammu & Kashmir, Ladakh - Mountains & Lakes
  {
    id: "leh-ladakh", // Already included above
    name: "Leh-Ladakh",
    lat: 34.1526,
    lon: 77.577,
    photos: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200"],
    popularity: 98,
    description: "High-altitude desert with stunning landscapes, monasteries, and adventure.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ladakh",
    tags: ["mountains", "adventure", "nature", "culture"],
  },
  {
    id: "srinagar",
    name: "Srinagar",
    lat: 34.0837,
    lon: 74.7973,
    photos: ["https://images.unsplash.com/photo-1597074866923-dc0589150184?w=1200"],
    popularity: 97,
    description: "Summer capital of J&K, famous for Dal Lake and houseboats.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Srinagar",
    tags: ["lakes", "mountains", "nature", "romantic"],
  },
  {
    id: "gulmarg",
    name: "Gulmarg",
    lat: 34.0484,
    lon: 74.3805,
    photos: ["https://images.unsplash.com/photo-1551582045-6ec9c11d8697?w=1200"],
    popularity: 94,
    description: "Meadow of Flowers, premier skiing destination with cable car.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gulmarg",
    tags: ["mountains", "snow", "adventure", "skiing"],
  },
  {
    id: "pahalgam",
    name: "Pahalgam",
    lat: 34.0161,
    lon: 75.315,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 93,
    description: "Valley of Shepherds, base camp for Amarnath Yatra.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Pahalgam",
    tags: ["mountains", "nature", "adventure", "spiritual"],
  },
  {
    id: "sonmarg",
    name: "Sonmarg",
    lat: 34.3,
    lon: 75.3,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 91,
    description: "Meadow of Gold with Thajiwas Glacier and trekking routes.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sonmarg",
    tags: ["mountains", "nature", "adventure", "glacier"],
  },
  {
    id: "pangong-lake",
    name: "Pangong Lake",
    lat: 33.7,
    lon: 78.9,
    photos: ["https://images.unsplash.com/photo-1597074866923-dc0589150184?w=1200"],
    popularity: 96,
    description: "Stunning high-altitude lake changing colors through the day.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Pangong_Tso",
    tags: ["lakes", "mountains", "nature", "scenic"],
  },
  {
    id: "nubra-valley",
    name: "Nubra Valley",
    lat: 34.6585,
    lon: 77.598,
    photos: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200"],
    popularity: 95,
    description: "Valley of Flowers with sand dunes and double-humped camels.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Nubra_Valley",
    tags: ["mountains", "desert", "nature", "adventure"],
  },
  {
    id: "kargil",
    name: "Kargil",
    lat: 34.5539,
    lon: 76.1313,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 79,
    description: "Strategic town on Srinagar-Leh highway with war memorial.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kargil",
    tags: ["mountains", "history", "adventure"],
  },

  // Goa - Beaches & Nightlife
  {
    id: "goa", // Already included above
    name: "Goa",
    lat: 15.2993,
    lon: 74.124,
    photos: ["https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200"],
    popularity: 99,
    description: "Beach paradise with Portuguese heritage, perfect for relaxation and water sports.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Goa",
    tags: ["beach", "party", "relaxation", "heritage"],
  },
  {
    id: "north-goa",
    name: "North Goa",
    lat: 15.545,
    lon: 73.8273,
    photos: ["https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200"],
    popularity: 95,
    description: "Famous for nightlife, beach parties, and water sports.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/North_Goa_district",
    tags: ["beach", "party", "adventure", "nightlife"],
  },
  {
    id: "south-goa",
    name: "South Goa",
    lat: 15.0992,
    lon: 74.124,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 92,
    description: "Peaceful beaches, luxury resorts, and Portuguese heritage.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/South_Goa_district",
    tags: ["beach", "relaxation", "heritage", "luxury"],
  },

  // Kerala - God's Own Country
  {
    id: "kerala-backwaters", // Already included above
    name: "Kerala Backwaters",
    lat: 9.9312,
    lon: 76.2673,
    photos: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200"],
    popularity: 96,
    description: "Serene network of lagoons, lakes, and canals with houseboat cruises.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kerala_backwaters",
    tags: ["nature", "backwaters", "relaxation", "scenic"],
  },
  {
    id: "munnar",
    name: "Munnar",
    lat: 10.0889,
    lon: 77.0595,
    photos: ["https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200"],
    popularity: 94,
    description: "Hill station with tea plantations and scenic mountain views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Munnar",
    tags: ["mountains", "nature", "tea", "romantic"],
  },
  {
    id: "kochi",
    name: "Kochi (Cochin)",
    lat: 9.9312,
    lon: 76.2673,
    photos: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200"],
    popularity: 89,
    description: "Port city with colonial history, Chinese fishing nets, and backwaters.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kochi",
    tags: ["heritage", "culture", "backwaters", "coastal"],
  },
  {
    id: "kovalam",
    name: "Kovalam",
    lat: 8.4004,
    lon: 76.979,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 91,
    description: "Beach town famous for lighthouse beach and Ayurvedic resorts.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kovalam",
    tags: ["beach", "relaxation", "wellness", "coastal"],
  },
  {
    id: "varkala",
    name: "Varkala",
    lat: 8.7379,
    lon: 76.7163,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 89,
    description: "Cliff beach with natural springs and spiritual significance.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Varkala",
    tags: ["beach", "spiritual", "nature", "relaxation"],
  },
  {
    id: "thekkady",
    name: "Thekkady",
    lat: 9.5915,
    lon: 77.1601,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 88,
    description: "Wildlife sanctuary with Periyar Lake and spice plantations.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Thekkady",
    tags: ["wildlife", "nature", "adventure", "scenic"],
  },
  {
    id: "wayanad",
    name: "Wayanad",
    lat: 11.6854,
    lon: 76.132,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 87,
    description: "Hill station with waterfalls, wildlife, and coffee plantations.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Wayanad_district",
    tags: ["mountains", "nature", "wildlife", "coffee"],
  },
  {
    id: "kumarakom",
    name: "Kumarakom",
    lat: 9.6177,
    lon: 76.4281,
    photos: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200"],
    popularity: 90,
    description: "Backwater destination with bird sanctuary and luxury resorts.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kumarakom",
    tags: ["backwaters", "nature", "relaxation", "birds"],
  },
  {
    id: "alleppey",
    name: "Alleppey (Alappuzha)",
    lat: 9.4981,
    lon: 76.3388,
    photos: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200"],
    popularity: 94,
    description: "Venice of the East with backwater houseboat experiences.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Alappuzha",
    tags: ["backwaters", "nature", "relaxation", "houseboat"],
  },

  // Tamil Nadu - Temples & Culture
  {
    id: "ooty",
    name: "Ooty",
    lat: 11.4102,
    lon: 76.695,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 93,
    description: "Queen of Hill Stations with tea gardens and toy train.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ooty",
    tags: ["mountains", "nature", "tea", "romantic"],
  },
  {
    id: "kodaikanal",
    name: "Kodaikanal",
    lat: 10.2381,
    lon: 77.4892,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 91,
    description: "Princess of Hill Stations with lakes and waterfalls.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kodaikanal",
    tags: ["mountains", "lakes", "nature", "romantic"],
  },
  {
    id: "madurai",
    name: "Madurai",
    lat: 9.9252,
    lon: 78.1198,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 87,
    description: "Temple city with the famous Meenakshi Amman Temple.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Madurai",
    tags: ["temple", "heritage", "culture", "spiritual"],
  },
  {
    id: "thanjavur",
    name: "Thanjavur",
    lat: 10.787,
    lon: 79.1378,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 80,
    description: "Home to Brihadeeswarar Temple, UNESCO World Heritage Site.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Thanjavur",
    tags: ["temple", "heritage", "culture", "art"],
  },
  {
    id: "kanyakumari",
    name: "Kanyakumari",
    lat: 8.0883,
    lon: 77.5385,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 92,
    description: "Southernmost tip of India where three seas meet.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kanyakumari",
    tags: ["coastal", "scenic", "spiritual", "sunrise"],
  },
  {
    id: "rameswaram",
    name: "Rameswaram",
    lat: 9.2876,
    lon: 79.3129,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 87,
    description: "Sacred pilgrimage site with Ramanathaswamy Temple.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Rameswaram",
    tags: ["spiritual", "temple", "coastal", "heritage"],
  },
  {
    id: "mahabalipuram",
    name: "Mahabalipuram",
    lat: 12.6269,
    lon: 80.1932,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 86,
    description: "Ancient port city with rock-cut temples and Shore Temple.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mahabalipuram",
    tags: ["heritage", "temple", "coastal", "history"],
  },
  {
    id: "pondicherry",
    name: "Pondicherry",
    lat: 11.9416,
    lon: 79.8083,
    photos: ["https://images.unsplash.com/photo-1558431382-27e303142255?w=1200"],
    popularity: 93,
    description: "French colonial town with beaches, spiritual centers, and unique charm.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Puducherry",
    tags: ["beach", "heritage", "relaxation", "culture"],
  },
  {
    id: "coonoor",
    name: "Coonoor",
    lat: 11.3557,
    lon: 76.7959,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 82,
    description: "Hill station with tea estates and scenic viewpoints.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Coonoor",
    tags: ["mountains", "tea", "nature", "romantic"],
  },

  // Karnataka - Gardens & Heritage
  {
    id: "mysore",
    name: "Mysore",
    lat: 12.2958,
    lon: 76.6394,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 91,
    description: "City of Palaces, known for Mysore Palace, silk sarees, and sandalwood.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mysore",
    tags: ["heritage", "culture", "palace", "shopping"],
  },
  {
    id: "coorg",
    name: "Coorg (Kodagu)",
    lat: 12.3375,
    lon: 75.8069,
    photos: ["https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200"],
    popularity: 94,
    description: "Scotland of India with coffee plantations and waterfalls.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kodagu_district",
    tags: ["mountains", "coffee", "nature", "scenic"],
  },
  {
    id: "hampi",
    name: "Hampi",
    lat: 15.335,
    lon: 76.46,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 93,
    description: "UNESCO World Heritage Site with Vijayanagara Empire ruins.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Hampi",
    tags: ["heritage", "history", "temple", "ruins"],
  },
  {
    id: "gokarna",
    name: "Gokarna",
    lat: 14.55,
    lon: 74.3167,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 88,
    description: "Peaceful beach town with temples and hippie culture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gokarna,_Karnataka",
    tags: ["beach", "spiritual", "backpacking", "nature"],
  },
  {
    id: "chikmagalur",
    name: "Chikmagalur",
    lat: 13.3161,
    lon: 75.772,
    photos: ["https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200"],
    popularity: 85,
    description: "Coffee land with hills, waterfalls, and trekking trails.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chikmagalur",
    tags: ["mountains", "coffee", "nature", "trekking"],
  },
  {
    id: "badami",
    name: "Badami",
    lat: 15.9149,
    lon: 75.6765,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 80,
    description: "Cave temples and rock-cut architecture from Chalukya dynasty.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Badami",
    tags: ["heritage", "temple", "history", "caves"],
  },
  {
    id: "belur-halebidu",
    name: "Belur-Halebidu",
    lat: 13.1656,
    lon: 75.865,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 79,
    description: "Hoysala temples with intricate stone carvings.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Belur",
    tags: ["heritage", "temple", "art", "history"],
  },

  // Northeast India - Unexplored Beauty
  {
    id: "sikkim",
    name: "Sikkim (Gangtok)",
    lat: 27.3389,
    lon: 88.6065,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 94,
    description: "Himalayan state with monasteries, Kanchenjunga views, and organic farming.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sikkim",
    tags: ["mountains", "nature", "adventure", "spiritual"],
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    lat: 27.041,
    lon: 88.2663,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 93,
    description: "Queen of the Hills with tea gardens and Himalayan railway.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Darjeeling",
    tags: ["mountains", "tea", "nature", "heritage"],
  },
  {
    id: "shillong",
    name: "Shillong",
    lat: 25.5788,
    lon: 91.8933,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 90,
    description: "Scotland of the East with waterfalls and music culture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Shillong",
    tags: ["mountains", "nature", "waterfalls", "culture"],
  },
  {
    id: "meghalaya",
    name: "Cherrapunji (Meghalaya)",
    lat: 25.263,
    lon: 91.7324,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 89,
    description: "Wettest place on Earth with living root bridges.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Cherrapunji",
    tags: ["nature", "waterfalls", "adventure", "scenic"],
  },
  {
    id: "kaziranga",
    name: "Kaziranga National Park",
    lat: 26.5775,
    lon: 93.1711,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 88,
    description: "UNESCO site with one-horned rhinoceros and wildlife.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kaziranga_National_Park",
    tags: ["wildlife", "nature", "adventure", "safari"],
  },
  {
    id: "arunachal-pradesh",
    name: "Tawang (Arunachal Pradesh)",
    lat: 27.586,
    lon: 91.859,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 87,
    description: "Himalayan town with Tawang Monastery and stunning landscapes.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Tawang",
    tags: ["mountains", "spiritual", "nature", "adventure"],
  },
  {
    id: "nagaland",
    name: "Kohima (Nagaland)",
    lat: 25.6747,
    lon: 94.1077,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 78,
    description: "Tribal culture, Hornbill Festival, and war cemetery.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kohima",
    tags: ["culture", "festival", "history", "tribal"],
  },
  {
    id: "majuli",
    name: "Majuli",
    lat: 26.95,
    lon: 94.2167,
    photos: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200"],
    popularity: 81,
    description: "World's largest river island in Brahmaputra with monasteries.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Majuli",
    tags: ["island", "river", "culture", "spiritual"],
  },

  // Gujarat - Heritage & Wildlife
  {
    id: "rann-of-kutch",
    name: "Rann of Kutch",
    lat: 23.834,
    lon: 69.6669,
    photos: ["https://images.unsplash.com/photo-1580836572829-d56024b4bbc8?w=1200"],
    popularity: 94,
    description: "White salt desert with Rann Utsav festival and handicrafts.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Rann_of_Kutch",
    tags: ["desert", "culture", "festival", "nature"],
  },
  {
    id: "gir-forest",
    name: "Gir Forest National Park",
    lat: 21.1248,
    lon: 70.7898,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 91,
    description: "Only home of Asiatic lions in the world.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gir_National_Park",
    tags: ["wildlife", "nature", "adventure", "safari"],
  },
  {
    id: "dwarka",
    name: "Dwarka",
    lat: 22.2442,
    lon: 68.9685,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 86,
    description: "Ancient city and one of the Char Dham pilgrimage sites.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Dwarka",
    tags: ["spiritual", "temple", "coastal", "heritage"],
  },
  {
    id: "somnath",
    name: "Somnath",
    lat: 20.888,
    lon: 70.4013,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 85,
    description: "First among twelve Jyotirlinga shrines of Shiva.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Somnath",
    tags: ["spiritual", "temple", "coastal", "heritage"],
  },
  {
    id: "saputara",
    name: "Saputara",
    lat: 20.5924,
    lon: 73.7507,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 79,
    description: "Gujarat's only hill station with lake and tribal culture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Saputara",
    tags: ["mountains", "lakes", "nature", "culture"],
  },
  {
    id: "champaner-pavagadh",
    name: "Champaner-Pavagadh",
    lat: 22.487,
    lon: 73.533,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 78,
    description: "UNESCO World Heritage Site with forts and temples.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Champaner-Pavagadh_Archaeological_Park",
    tags: ["heritage", "fort", "temple", "history"],
  },

  // Maharashtra - Caves & Beaches
  {
    id: "lonavala",
    name: "Lonavala",
    lat: 18.7537,
    lon: 73.4063,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 89,
    description: "Hill station near Mumbai with caves, waterfalls, and chikki.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lonavala",
    tags: ["mountains", "nature", "waterfalls", "caves"],
  },
  {
    id: "mahabaleshwar",
    name: "Mahabaleshwar",
    lat: 17.9236,
    lon: 73.6577,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 87,
    description: "Hill station with strawberry farms and viewpoints.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mahabaleshwar",
    tags: ["mountains", "nature", "scenic", "strawberry"],
  },
  {
    id: "ajanta-ellora",
    name: "Ajanta-Ellora Caves",
    lat: 20.5519,
    lon: 75.7033,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 93,
    description: "UNESCO World Heritage rock-cut caves with ancient art.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ajanta_Caves",
    tags: ["heritage", "caves", "art", "history"],
  },
  {
    id: "alibaug",
    name: "Alibaug",
    lat: 18.6414,
    lon: 72.8722,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 86,
    description: "Beach town near Mumbai with forts and water sports.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Alibaug",
    tags: ["beach", "fort", "relaxation", "coastal"],
  },
  {
    id: "nashik",
    name: "Nashik",
    lat: 19.9975,
    lon: 73.7898,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 84,
    description: "Wine capital of India and religious pilgrimage site.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Nashik",
    tags: ["spiritual", "wine", "culture", "heritage"],
  },
  {
    id: "matheran",
    name: "Matheran",
    lat: 18.9854,
    lon: 73.2647,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 83,
    description: "Asia's only automobile-free hill station with toy train.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Matheran",
    tags: ["mountains", "nature", "romantic", "heritage"],
  },
  {
    id: "shirdi",
    name: "Shirdi",
    lat: 19.7645,
    lon: 74.4777,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 89,
    description: "Pilgrimage town with Sai Baba Temple.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Shirdi",
    tags: ["spiritual", "temple", "pilgrimage"],
  },

  // Punjab - Heritage & Culture
  {
    id: "amritsar",
    name: "Amritsar",
    lat: 31.634,
    lon: 74.8723,
    photos: ["https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=1200"],
    popularity: 95,
    description: "Home to the Golden Temple, spiritual center of Sikhism and vibrant Punjabi culture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Amritsar",
    tags: ["spiritual", "heritage", "food", "culture"],
  },
  {
    id: "chandigarh",
    name: "Chandigarh",
    lat: 30.7333,
    lon: 76.7794,
    photos: ["https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=1200"],
    popularity: 85,
    description: "Planned city by Le Corbusier with modern architecture and Rock Garden.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chandigarh",
    tags: ["city", "modern", "gardens", "architecture"],
  },

  // Madhya Pradesh - Tiger Country & Heritage
  {
    id: "khajuraho",
    name: "Khajuraho",
    lat: 24.8318,
    lon: 79.9199,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 89,
    description: "UNESCO World Heritage Site with erotic temple sculptures.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Khajuraho_Group_of_Monuments",
    tags: ["heritage", "temple", "art", "history"],
  },
  {
    id: "bhopal",
    name: "Bhopal",
    lat: 23.2599,
    lon: 77.4126,
    photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200"],
    popularity: 83,
    description: "City of Lakes with Mughal heritage and modern development.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bhopal",
    tags: ["lakes", "heritage", "culture", "city"],
  },
  {
    id: "bandhavgarh",
    name: "Bandhavgarh National Park",
    lat: 23.6697,
    lon: 80.9738,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 88,
    description: "Highest density of Bengal tigers in India.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bandhavgarh_National_Park",
    tags: ["wildlife", "nature", "adventure", "safari"],
  },
  {
    id: "kanha",
    name: "Kanha National Park",
    lat: 22.3348,
    lon: 80.6119,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 87,
    description: "Tiger reserve that inspired Kipling's Jungle Book.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kanha_Tiger_Reserve",
    tags: ["wildlife", "nature", "adventure", "safari"],
  },
  {
    id: "pachmarhi",
    name: "Pachmarhi",
    lat: 22.4676,
    lon: 78.4336,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 83,
    description: "Hill station with waterfalls, caves, and Satpura range views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Pachmarhi",
    tags: ["mountains", "nature", "waterfalls", "caves"],
  },
  {
    id: "gwalior",
    name: "Gwalior",
    lat: 26.2183,
    lon: 78.1828,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 81,
    description: "Historic city with hilltop fort and palaces.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gwalior",
    tags: ["heritage", "fort", "history", "culture"],
  },
  {
    id: "ujjain",
    name: "Ujjain",
    lat: 23.1765,
    lon: 75.7885,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 83,
    description: "Ancient city and one of the seven sacred cities in Hinduism.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ujjain",
    tags: ["spiritual", "temple", "heritage", "culture"],
  },
  {
    id: "orchha",
    name: "Orchha",
    lat: 25.3519,
    lon: 78.6422,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 79,
    description: "Medieval town with palaces and temples on Betwa River.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Orchha",
    tags: ["heritage", "palace", "temple", "history"],
  },
  {
    id: "sanchi",
    name: "Sanchi",
    lat: 23.4793,
    lon: 77.7397,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 78,
    description: "Buddhist complex with Great Stupa, UNESCO World Heritage Site.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sanchi",
    tags: ["heritage", "spiritual", "buddhist", "history"],
  },

  // Chhattisgarh - Tribal & Nature
  {
    id: "chitrakote-falls",
    name: "Chitrakote Falls",
    lat: 19.2013,
    lon: 81.8441,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 78,
    description: "India's widest waterfall, called Niagara of India.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chitrakote_Falls",
    tags: ["nature", "waterfalls", "scenic"],
  },

  // Odisha - Temples & Beaches
  {
    id: "puri",
    name: "Puri",
    lat: 19.8135,
    lon: 85.8312,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 92,
    description: "Sacred city with Jagannath Temple and beach.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Puri",
    tags: ["spiritual", "temple", "beach", "pilgrimage"],
  },
  {
    id: "konark",
    name: "Konark",
    lat: 19.8876,
    lon: 86.0945,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 88,
    description: "UNESCO World Heritage Sun Temple in chariot shape.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Konark_Sun_Temple",
    tags: ["heritage", "temple", "coastal", "history"],
  },
  {
    id: "bhubaneswar",
    name: "Bhubaneswar",
    lat: 20.2961,
    lon: 85.8245,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 84,
    description: "Temple city of India with ancient architecture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bhubaneswar",
    tags: ["temple", "heritage", "culture", "city"],
  },
  {
    id: "chilika-lake",
    name: "Chilika Lake",
    lat: 19.7151,
    lon: 85.321,
    photos: ["https://images.unsplash.com/photo-1597074866923-dc0589150184?w=1200"],
    popularity: 86,
    description: "Asia's largest brackish water lagoon with migratory birds.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chilika_Lake",
    tags: ["lakes", "nature", "birds", "scenic"],
  },
  {
    id: "simlipal",
    name: "Simlipal National Park",
    lat: 21.731,
    lon: 86.3088,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 80,
    description: "Tiger reserve with waterfalls and tribal villages.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Simlipal_National_Park",
    tags: ["wildlife", "nature", "waterfalls", "tribal"],
  },

  // West Bengal - Culture & Hills
  {
    id: "kalimpong",
    name: "Kalimpong",
    lat: 27.0669,
    lon: 88.468,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 83,
    description: "Hill station with Buddhist monasteries and flower nurseries.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kalimpong",
    tags: ["mountains", "spiritual", "nature", "flowers"],
  },
  {
    id: "sundarbans",
    name: "Sundarbans",
    lat: 21.9497,
    lon: 89.1833,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 89,
    description: "Largest mangrove forest and home to Royal Bengal Tigers.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sundarbans",
    tags: ["wildlife", "nature", "mangrove", "unesco"],
  },
  {
    id: "digha",
    name: "Digha",
    lat: 21.6783,
    lon: 87.526,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 80,
    description: "Popular beach resort town in West Bengal.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Digha",
    tags: ["beach", "relaxation", "coastal"],
  },

  // Andaman & Nicobar Islands
  {
    id: "andaman-nicobar", // Already included above
    name: "Andaman & Nicobar",
    lat: 11.7401,
    lon: 92.6586,
    photos: ["https://images.unsplash.com/photo-1599852439054-e8c8e61dd337?w=1200"],
    popularity: 96,
    description: "Tropical paradise with pristine beaches, coral reefs, and water sports.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Andaman_and_Nicobar_Islands",
    tags: ["beach", "island", "adventure", "nature"],
  },
  {
    id: "havelock-island",
    name: "Havelock Island",
    lat: 11.9934,
    lon: 92.9653,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 95,
    description: "Famous for Radhanagar Beach and scuba diving.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Havelock_Island",
    tags: ["beach", "island", "diving", "scenic"],
  },
  {
    id: "neil-island",
    name: "Neil Island",
    lat: 11.8328,
    lon: 93.0493,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 93,
    description: "Small island with natural rock formations and coral reefs.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Neil_Island",
    tags: ["beach", "island", "nature", "relaxation"],
  },
  {
    id: "port-blair",
    name: "Port Blair",
    lat: 11.6234,
    lon: 92.7265,
    photos: ["https://images.unsplash.com/photo-1599852439054-e8c8e61dd337?w=1200"],
    popularity: 92,
    description: "Capital with Cellular Jail and water sports.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Port_Blair",
    tags: ["heritage", "beach", "history", "island"],
  },

  // Lakshadweep
  {
    id: "lakshadweep",
    name: "Lakshadweep",
    lat: 10.5669,
    lon: 72.6417,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 94,
    description: "Coral islands with lagoons and water sports.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lakshadweep",
    tags: ["beach", "island", "diving", "coral"],
  },

  // Andhra Pradesh
  {
    id: "tirupati",
    name: "Tirupati",
    lat: 13.6288,
    lon: 79.4192,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 97,
    description: "Major pilgrimage site with Venkateswara Temple.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Tirupati",
    tags: ["spiritual", "temple", "pilgrimage", "heritage"],
  },
  {
    id: "visakhapatnam",
    name: "Visakhapatnam",
    lat: 17.6869,
    lon: 83.2185,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 88,
    description: "Port city with beaches and Araku Valley nearby.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Visakhapatnam",
    tags: ["beach", "city", "coastal", "modern"],
  },
  {
    id: "araku-valley",
    name: "Araku Valley",
    lat: 18.3273,
    lon: 82.8756,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 85,
    description: "Hill station with coffee plantations and tribal culture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Araku_Valley",
    tags: ["mountains", "coffee", "nature", "tribal"],
  },
  {
    id: "amaravati",
    name: "Amaravati",
    lat: 16.5745,
    lon: 80.358,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 78,
    description: "Ancient Buddhist site and new capital city.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Amaravati,_Andhra_Pradesh",
    tags: ["heritage", "spiritual", "history", "buddhist"],
  },

  // Telangana
  {
    id: "warangal",
    name: "Warangal",
    lat: 17.9689,
    lon: 79.5941,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 81,
    description: "Historic city with Kakatiya dynasty forts and temples.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Warangal",
    tags: ["heritage", "fort", "temple", "history"],
  },
  {
    id: "ramoji-film-city",
    name: "Ramoji Film City",
    lat: 17.2543,
    lon: 78.6808,
    photos: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0648?w=1200"],
    popularity: 86,
    description: "World's largest film city with themed attractions.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ramoji_Film_City",
    tags: ["entertainment", "film", "theme-park", "modern"],
  },

  // Bihar & Jharkhand
  {
    id: "bodh-gaya",
    name: "Bodh Gaya",
    lat: 24.6952,
    lon: 84.9914,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 93,
    description: "Where Buddha attained enlightenment, major Buddhist pilgrimage site.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bodh_Gaya",
    tags: ["spiritual", "buddhist", "heritage", "pilgrimage"],
  },
  {
    id: "patna",
    name: "Patna",
    lat: 25.5941,
    lon: 85.1376,
    photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200"],
    popularity: 80,
    description: "Ancient city on Ganges with Mahabodhi Temple nearby.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Patna",
    tags: ["heritage", "city", "river", "culture"],
  },
  {
    id: "ranchi",
    name: "Ranchi",
    lat: 23.3441,
    lon: 85.3096,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 79,
    description: "City of waterfalls with natural beauty and tribal culture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ranchi",
    tags: ["waterfalls", "nature", "tribal", "city"],
  },
  {
    id: "jamshedpur",
    name: "Jamshedpur",
    lat: 22.8046,
    lon: 86.2029,
    photos: ["https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1200"],
    popularity: 77,
    description: "Planned industrial city with parks and lakes.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jamshedpur",
    tags: ["city", "modern", "lakes", "industrial"],
  },
  {
    id: "netarhat",
    name: "Netarhat",
    lat: 23.4711,
    lon: 84.2614,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 76,
    description: "Queen of Chotanagpur with sunrise and sunset points.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Netarhat",
    tags: ["mountains", "nature", "scenic", "sunrise"],
  },

  // Additional Heritage Sites
  {
    id: "fatehpur-sikri",
    name: "Fatehpur Sikri",
    lat: 27.0945,
    lon: 77.6619,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 89,
    description: "Abandoned Mughal capital, UNESCO World Heritage Site.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Fatehpur_Sikri",
    tags: ["heritage", "history", "mughal", "unesco"],
  },
  {
    id: "victoria-memorial",
    name: "Victoria Memorial",
    lat: 22.5448,
    lon: 88.3426,
    photos: ["https://images.unsplash.com/photo-1558431382-27e303142255?w=1200"],
    popularity: 88,
    description: "Iconic Kolkata monument with museum and gardens.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Victoria_Memorial,_Kolkata",
    tags: ["heritage", "museum", "gardens", "colonial"],
  },
  {
    id: "qutub-minar",
    name: "Qutub Minar",
    lat: 28.5244,
    lon: 77.1855,
    photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200"],
    popularity: 92,
    description: "Tallest brick minaret in the world, UNESCO World Heritage Site.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Qutb_Minar",
    tags: ["heritage", "monument", "history", "unesco"],
  },
  {
    id: "red-fort",
    name: "Red Fort",
    lat: 28.6562,
    lon: 77.241,
    photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200"],
    popularity: 93,
    description: "Historic Mughal fort in Delhi, symbol of India's independence.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Red_Fort",
    tags: ["heritage", "fort", "history", "mughal"],
  },
  {
    id: "india-gate",
    name: "India Gate",
    lat: 28.6129,
    lon: 77.2295,
    photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200"],
    popularity: 91,
    description: "War memorial and iconic landmark in New Delhi.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/India_Gate",
    tags: ["monument", "heritage", "memorial", "iconic"],
  },
  {
    id: "lotus-temple",
    name: "Lotus Temple",
    lat: 28.5535,
    lon: 77.2588,
    photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200"],
    popularity: 88,
    description: "Bahá'í House of Worship with distinctive lotus-shaped architecture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lotus_Temple",
    tags: ["spiritual", "architecture", "modern", "iconic"],
  },
  {
    id: "gateway-of-india",
    name: "Gateway of India",
    lat: 18.922,
    lon: 72.8347,
    photos: ["https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200"],
    popularity: 94,
    description: "Iconic arch monument on Mumbai waterfront.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gateway_of_India",
    tags: ["monument", "heritage", "coastal", "iconic"],
  },
  {
    id: "charminar",
    name: "Charminar",
    lat: 17.3616,
    lon: 78.4747,
    photos: ["https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1200"],
    popularity: 90,
    description: "Iconic monument and mosque in Hyderabad.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Charminar",
    tags: ["heritage", "monument", "architecture", "iconic"],
  },
  {
    id: "hawa-mahal",
    name: "Hawa Mahal",
    lat: 26.9239,
    lon: 75.8267,
    photos: ["https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200"],
    popularity: 93,
    description: "Palace of Winds in Jaipur with unique honeycomb architecture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Hawa_Mahal",
    tags: ["heritage", "palace", "architecture", "iconic"],
  },
  {
    id: "city-palace-jaipur",
    name: "City Palace Jaipur",
    lat: 26.9255,
    lon: 75.8237,
    photos: ["https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200"],
    popularity: 91,
    description: "Royal residence complex with museums and courtyards.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/City_Palace,_Jaipur",
    tags: ["heritage", "palace", "museum", "royal"],
  },
  {
    id: "amber-fort",
    name: "Amber Fort",
    lat: 26.9855,
    lon: 75.8513,
    photos: ["https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200"],
    popularity: 94,
    description: "Majestic fort with elephant rides and mirror palace.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Amber_Fort",
    tags: ["heritage", "fort", "palace", "royal"],
  },

  // More Beach Destinations
  {
    id: "tarkarli",
    name: "Tarkarli",
    lat: 16.0272,
    lon: 73.4667,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 83,
    description: "Pristine beaches in Maharashtra with water sports.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Tarkarli",
    tags: ["beach", "diving", "coastal", "adventure"],
  },
  {
    id: "gokarna-beaches",
    name: "Gokarna Beaches",
    lat: 14.55,
    lon: 74.3167,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 87,
    description: "Om Beach, Half Moon Beach, and Paradise Beach.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gokarna,_Karnataka",
    tags: ["beach", "backpacking", "nature", "scenic"],
  },
  {
    id: "kashid",
    name: "Kashid Beach",
    lat: 18.3986,
    lon: 72.9986,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 81,
    description: "White sand beach near Mumbai with water sports.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kashid",
    tags: ["beach", "coastal", "relaxation"],
  },
  {
    id: "diu",
    name: "Diu",
    lat: 20.7144,
    lon: 70.9873,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 86,
    description: "Island with Portuguese heritage and quiet beaches.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Diu,_India",
    tags: ["beach", "island", "heritage", "relaxation"],
  },
  {
    id: "daman",
    name: "Daman",
    lat: 20.414,
    lon: 72.8328,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 83,
    description: "Beach town with forts and Portuguese churches.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Daman,_India",
    tags: ["beach", "heritage", "fort", "coastal"],
  },
  {
    id: "marari-beach",
    name: "Marari Beach",
    lat: 9.6029,
    lon: 76.2986,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 82,
    description: "Peaceful Kerala beach with fishing villages.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Marari_Beach",
    tags: ["beach", "relaxation", "village", "coastal"],
  },
  {
    id: "bekal",
    name: "Bekal",
    lat: 12.3919,
    lon: 75.037,
    photos: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200"],
    popularity: 84,
    description: "Kerala beach with historic fort on cliff.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bekal",
    tags: ["beach", "fort", "heritage", "scenic"],
  },
  {
    id: "st-marys-island",
    name: "St. Mary's Island",
    lat: 13.8333,
    lon: 74.6667,
    photos: ["https://images.unsplash.com/photo-1599852439054-e8c8e61dd337?w=1200"],
    popularity: 80,
    description: "Unique hexagonal basaltic rock formations.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/St._Mary%27s_Islands",
    tags: ["island", "nature", "scenic", "unique"],
  },

  // More Wildlife Sanctuaries
  {
    id: "periyar",
    name: "Periyar Wildlife Sanctuary",
    lat: 9.4615,
    lon: 77.238,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 88,
    description: "Kerala tiger reserve with boat safaris on Periyar Lake.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Periyar_National_Park",
    tags: ["wildlife", "nature", "safari", "lakes"],
  },
  {
    id: "nagarhole",
    name: "Nagarhole National Park",
    lat: 12.0667,
    lon: 76.1,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 85,
    description: "Karnataka wildlife park with tigers and elephants.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Nagarhole_National_Park",
    tags: ["wildlife", "nature", "safari", "forest"],
  },
  {
    id: "keoladeo",
    name: "Keoladeo National Park",
    lat: 27.1594,
    lon: 77.5242,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 84,
    description: "Bharatpur bird sanctuary, UNESCO World Heritage Site.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Keoladeo_National_Park",
    tags: ["birds", "nature", "unesco", "wetland"],
  },
  {
    id: "sariska",
    name: "Sariska Tiger Reserve",
    lat: 27.293,
    lon: 76.3883,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 83,
    description: "Rajasthan tiger reserve with ancient temples.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sariska_Tiger_Reserve",
    tags: ["wildlife", "nature", "safari", "tigers"],
  },
  {
    id: "tadoba",
    name: "Tadoba National Park",
    lat: 20.25,
    lon: 79.3333,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 86,
    description: "Maharashtra's oldest and largest tiger reserve.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Tadoba_Andhari_Tiger_Reserve",
    tags: ["wildlife", "nature", "safari", "tigers"],
  },
  {
    id: "pench",
    name: "Pench National Park",
    lat: 21.7053,
    lon: 79.2965,
    photos: ["https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200"],
    popularity: 84,
    description: "Tiger reserve on MP-Maharashtra border.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Pench_National_Park",
    tags: ["wildlife", "nature", "safari", "tigers"],
  },

  // More Hill Stations
  {
    id: "yercaud",
    name: "Yercaud",
    lat: 11.7769,
    lon: 78.2041,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 81,
    description: "Hill station in Tamil Nadu with coffee plantations.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Yercaud",
    tags: ["mountains", "coffee", "nature", "lakes"],
  },
  {
    id: "lavasa",
    name: "Lavasa",
    lat: 18.41,
    lon: 73.5089,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 80,
    description: "Planned hill city near Pune with Italian-style architecture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lavasa",
    tags: ["mountains", "modern", "lakes", "planned"],
  },
  {
    id: "horsley-hills",
    name: "Horsley Hills",
    lat: 13.6667,
    lon: 78.4167,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 79,
    description: "Andhra Pradesh hill station with wildlife sanctuary.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Horsley_Hills",
    tags: ["mountains", "nature", "wildlife", "scenic"],
  },
  {
    id: "panchgani",
    name: "Panchgani",
    lat: 17.9242,
    lon: 73.7997,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 85,
    description: "Hill station with Table Land plateau and strawberry farms.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Panchgani",
    tags: ["mountains", "nature", "strawberry", "scenic"],
  },
  {
    id: "malshej-ghat",
    name: "Malshej Ghat",
    lat: 19.35,
    lon: 73.7833,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 80,
    description: "Mountain pass with waterfalls and bird watching.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Malshej_Ghat",
    tags: ["mountains", "waterfalls", "birds", "nature"],
  },
  {
    id: "ranikhet",
    name: "Ranikhet",
    lat: 29.6436,
    lon: 79.4324,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 82,
    description: "Uttarakhand hill station with golf course and Himalayan views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ranikhet",
    tags: ["mountains", "nature", "scenic", "peaceful"],
  },
  {
    id: "kausani",
    name: "Kausani",
    lat: 29.84,
    lon: 79.6,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 81,
    description: "Hill station with panoramic Himalayan views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kausani",
    tags: ["mountains", "scenic", "nature", "peaceful"],
  },
  {
    id: "lansdowne",
    name: "Lansdowne",
    lat: 29.84,
    lon: 78.68,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 80,
    description: "Quiet hill station with colonial architecture.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lansdowne,_Uttarakhand",
    tags: ["mountains", "heritage", "nature", "peaceful"],
  },
  {
    id: "almora",
    name: "Almora",
    lat: 29.5971,
    lon: 79.659,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 83,
    description: "Cultural town with temples and Himalayan views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Almora",
    tags: ["mountains", "culture", "temple", "scenic"],
  },
  {
    id: "chakrata",
    name: "Chakrata",
    lat: 30.7033,
    lon: 77.8686,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 79,
    description: "Offbeat hill station with Tiger Falls.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chakrata",
    tags: ["mountains", "waterfalls", "nature", "offbeat"],
  },

  // Desert Adventures
  {
    id: "sam-sand-dunes",
    name: "Sam Sand Dunes",
    lat: 26.907,
    lon: 70.805,
    photos: ["https://images.unsplash.com/photo-1580836572829-d56024b4bbc8?w=1200"],
    popularity: 87,
    description: "Desert camp experience near Jaisalmer with camel safaris.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sam,_Jaisalmer",
    tags: ["desert", "adventure", "camping", "camel"],
  },
  {
    id: "khuri",
    name: "Khuri Sand Dunes",
    lat: 26.8186,
    lon: 70.7367,
    photos: ["https://images.unsplash.com/photo-1580836572829-d56024b4bbc8?w=1200"],
    popularity: 79,
    description: "Less crowded desert village near Jaisalmer.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Khuri",
    tags: ["desert", "village", "camping", "offbeat"],
  },

  // River & Lake Destinations
  {
    id: "ranakpur",
    name: "Ranakpur",
    lat: 25.1114,
    lon: 73.476,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 85,
    description: "Jain temple complex with intricate marble carvings.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ranakpur",
    tags: ["temple", "heritage", "marble", "spiritual"],
  },
  {
    id: "nakki-lake",
    name: "Nakki Lake",
    lat: 24.5926,
    lon: 72.7156,
    photos: ["https://images.unsplash.com/photo-1597074866923-dc0589150184?w=1200"],
    popularity: 82,
    description: "Sacred lake in Mount Abu with boating.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Nakki_Lake",
    tags: ["lakes", "scenic", "boating", "mountains"],
  },
  {
    id: "bhimtal",
    name: "Bhimtal",
    lat: 29.3468,
    lon: 79.5627,
    photos: ["https://images.unsplash.com/photo-1597074866923-dc0589150184?w=1200"],
    popularity: 83,
    description: "Lake town in Uttarakhand with island aquarium.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Bhimtal",
    tags: ["lakes", "mountains", "nature", "boating"],
  },
  {
    id: "sattal",
    name: "Sattal",
    lat: 29.3833,
    lon: 79.55,
    photos: ["https://images.unsplash.com/photo-1597074866923-dc0589150184?w=1200"],
    popularity: 81,
    description: "Cluster of seven freshwater lakes for nature lovers.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sattal",
    tags: ["lakes", "nature", "birds", "peaceful"],
  },
  {
    id: "pichola-lake",
    name: "Lake Pichola",
    lat: 24.5761,
    lon: 73.6813,
    photos: ["https://images.unsplash.com/photo-1597074866923-dc0589150184?w=1200"],
    popularity: 91,
    description: "Udaipur's artificial lake with palaces on islands.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lake_Pichola",
    tags: ["lakes", "palace", "scenic", "romantic"],
  },
  {
    id: "loktak-lake",
    name: "Loktak Lake",
    lat: 24.55,
    lon: 93.7833,
    photos: ["https://images.unsplash.com/photo-1597074866923-dc0589150184?w=1200"],
    popularity: 83,
    description: "Largest freshwater lake in Northeast with floating islands.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Loktak_Lake",
    tags: ["lakes", "nature", "unique", "scenic"],
  },
  {
    id: "hussain-sagar",
    name: "Hussain Sagar",
    lat: 17.4239,
    lon: 78.4738,
    photos: ["https://images.unsplash.com/photo-1597074866923-dc0589150184?w=1200"],
    popularity: 86,
    description: "Heart-shaped lake in Hyderabad with Buddha statue.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Hussain_Sagar",
    tags: ["lakes", "city", "statue", "scenic"],
  },

  // Waterfalls
  {
    id: "jog-falls",
    name: "Jog Falls",
    lat: 14.2295,
    lon: 74.8128,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 89,
    description: "India's second-highest plunge waterfall in Karnataka.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jog_Falls",
    tags: ["waterfalls", "nature", "scenic", "monsoon"],
  },
  {
    id: "dudhsagar-falls",
    name: "Dudhsagar Falls",
    lat: 15.3144,
    lon: 74.3144,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 91,
    description: "Four-tiered waterfall on Goa-Karnataka border.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Dudhsagar_Falls",
    tags: ["waterfalls", "nature", "trek", "scenic"],
  },
  {
    id: "athirapally-falls",
    name: "Athirapally Falls",
    lat: 10.2851,
    lon: 76.5702,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 88,
    description: "Kerala's largest waterfall, nicknamed Niagara of India.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Athirappilly_Falls",
    tags: ["waterfalls", "nature", "scenic", "forest"],
  },
  {
    id: "nohkalikai-falls",
    name: "Nohkalikai Falls",
    lat: 25.2743,
    lon: 91.7155,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 89,
    description: "India's tallest plunge waterfall in Meghalaya.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Nohkalikai_Falls",
    tags: ["waterfalls", "nature", "scenic", "meghalaya"],
  },
  {
    id: "elephant-falls",
    name: "Elephant Falls",
    lat: 25.5336,
    lon: 91.8909,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 85,
    description: "Three-tiered waterfall near Shillong.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Elephant_Falls",
    tags: ["waterfalls", "nature", "scenic", "accessible"],
  },
  {
    id: "hogenakkal-falls",
    name: "Hogenakkal Falls",
    lat: 12.12,
    lon: 77.78,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 86,
    description: "Carbonatite rocks waterfall on Kaveri River.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Hogenakkal_Falls",
    tags: ["waterfalls", "nature", "river", "coracle"],
  },

  // Trekking & Adventure Destinations
  {
    id: "valley-of-flowers",
    name: "Valley of Flowers",
    lat: 30.7333,
    lon: 79.6,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 94,
    description: "UNESCO World Heritage Site with alpine meadows and flowers.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Valley_of_Flowers_National_Park",
    tags: ["trek", "nature", "flowers", "unesco"],
  },
  {
    id: "hemkund-sahib",
    name: "Hemkund Sahib",
    lat: 30.7167,
    lon: 79.5667,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 90,
    description: "Sikh pilgrimage site at high altitude with glacial lake.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Hemkund_Sahib",
    tags: ["spiritual", "trek", "lake", "pilgrimage"],
  },
  {
    id: "roopkund",
    name: "Roopkund",
    lat: 30.2,
    lon: 79.7333,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 84,
    description: "Mysterious skeleton lake trek in Uttarakhand.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Roopkund",
    tags: ["trek", "mountains", "adventure", "mystery"],
  },
  {
    id: "chadar-trek",
    name: "Chadar Trek",
    lat: 34.0,
    lon: 77.5,
    photos: ["https://images.unsplash.com/photo-1551582045-6ec9c11d8697?w=1200"],
    popularity: 92,
    description: "Walking on frozen Zanskar River in Ladakh.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chadar_Trek",
    tags: ["trek", "adventure", "ice", "extreme"],
  },
  {
    id: "markha-valley",
    name: "Markha Valley Trek",
    lat: 33.9833,
    lon: 77.4,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 86,
    description: "Popular Ladakh trek through villages and monasteries.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Markha_Valley",
    tags: ["trek", "mountains", "culture", "adventure"],
  },
  {
    id: "sandakphu",
    name: "Sandakphu Trek",
    lat: 27.0,
    lon: 88.0167,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 87,
    description: "Highest peak in West Bengal with views of four highest peaks.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sandakphu",
    tags: ["trek", "mountains", "scenic", "nepal-border"],
  },
  {
    id: "triund",
    name: "Triund Trek",
    lat: 32.2479,
    lon: 76.3214,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 88,
    description: "Easy trek near Dharamshala with stunning Dhauladhar views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Triund",
    tags: ["trek", "mountains", "camping", "easy"],
  },
  {
    id: "har-ki-dun",
    name: "Har Ki Dun Trek",
    lat: 31.15,
    lon: 78.4,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 85,
    description: "Valley of Gods trek in Garhwal Himalayas.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Har_Ki_Dun",
    tags: ["trek", "mountains", "valley", "nature"],
  },
  {
    id: "chopta-tungnath",
    name: "Chopta-Tungnath",
    lat: 30.47,
    lon: 79.2167,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 89,
    description: "Mini Switzerland with world's highest Shiva temple.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chopta",
    tags: ["trek", "spiritual", "mountains", "temple"],
  },
  {
    id: "kedarkantha",
    name: "Kedarkantha Trek",
    lat: 31.0217,
    lon: 78.4128,
    photos: ["https://images.unsplash.com/photo-1551582045-6ec9c11d8697?w=1200"],
    popularity: 90,
    description: "Popular winter trek with panoramic Himalayan views.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Kedarkantha",
    tags: ["trek", "mountains", "winter", "snow"],
  },

  // Spiritual & Pilgrimage (Additional)
  {
    id: "mount-kailash",
    name: "Kailash Mansarovar",
    lat: 31.0686,
    lon: 81.3119,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 95,
    description: "Sacred mountain pilgrimage through India-China route.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mount_Kailash",
    tags: ["spiritual", "pilgrimage", "mountains", "sacred"],
  },
  {
    id: "sabrimala",
    name: "Sabarimala",
    lat: 9.435,
    lon: 77.065,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 92,
    description: "Famous Ayyappa temple in Kerala hills.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Sabarimala",
    tags: ["spiritual", "temple", "pilgrimage", "mountains"],
  },
  {
    id: "guruvayur",
    name: "Guruvayur",
    lat: 10.5938,
    lon: 76.0393,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 88,
    description: "Major Krishna temple in Kerala.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Guruvayur",
    tags: ["spiritual", "temple", "pilgrimage"],
  },
  {
    id: "palitana",
    name: "Palitana Temples",
    lat: 21.5222,
    lon: 71.8283,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 86,
    description: "Largest cluster of Jain temples on Shatrunjaya hill.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Palitana_temples",
    tags: ["spiritual", "temple", "jain", "heritage"],
  },
  {
    id: "nathdwara",
    name: "Nathdwara",
    lat: 24.9333,
    lon: 73.8217,
    photos: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200"],
    popularity: 84,
    description: "Famous Krishna temple with Pichwai paintings.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Nathdwara",
    tags: ["spiritual", "temple", "art", "culture"],
  },
  {
    id: "madikeri",
    name: "Madikeri (Mercara)",
    lat: 12.4244,
    lon: 75.7382,
    photos: ["https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200"],
    popularity: 86,
    description: "Main town of Coorg with Abbey Falls and Raja's Seat.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Madikeri",
    tags: ["mountains", "coffee", "waterfalls", "scenic"],
  },
  {
    id: "talakona",
    name: "Talakona Falls",
    lat: 13.5833,
    lon: 79.5833,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 80,
    description: "Highest waterfall in Andhra Pradesh.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Talakona",
    tags: ["waterfalls", "nature", "trek", "forest"],
  },
  {
    id: "borra-caves",
    name: "Borra Caves",
    lat: 18.28,
    lon: 83.0333,
    photos: ["https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200"],
    popularity: 84,
    description: "Natural caves with stalactites and stalagmites.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Borra_Caves",
    tags: ["caves", "nature", "geology", "unique"],
  },
  {
    id: "lambasingi",
    name: "Lambasingi",
    lat: 17.95,
    lon: 82.5833,
    photos: ["https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200"],
    popularity: 81,
    description: "Only place in South India with snowfall.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lambasingi",
    tags: ["mountains", "snow", "nature", "unique"],
  },
  {
    id: "yelagiri",
    name: "Yelagiri",
    lat: 12.5833,
    lon: 78.6333,
    photos: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200"],
    popularity: 82,
    description: "Lesser-known hill station in Tamil Nadu.",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Yelagiri",
    tags: ["mountains", "nature", "offbeat", "adventure"],
  },
]

function calculateDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371 // Earth's radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180
  const dLon = ((lon2 - lon1) * Math.PI) / 180
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) * Math.sin(dLon / 2) * Math.sin(dLon / 2)
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
  return R * c
}

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url)
    const userLat = searchParams.get("lat")
    const userLon = searchParams.get("lon")
    const radius = searchParams.get("radius") // in km

    // Check cache
    if (cache && Date.now() - cache.ts < CACHE_TTL_MS) {
      let places = [...cache.data]

      if (userLat && userLon && radius) {
        const lat = Number.parseFloat(userLat)
        const lon = Number.parseFloat(userLon)
        const radiusKm = Number.parseFloat(radius)

        if (!isNaN(lat) && !isNaN(lon) && !isNaN(radiusKm) && radiusKm > 0) {
          places = places
            .map((place) => ({
              ...place,
              distance: calculateDistance(lat, lon, place.lat, place.lon),
            }))
            .filter((place) => place.distance <= radiusKm)
            .sort((a, b) => {
              // Higher popularity comes first
              const popDiff = b.popularity - a.popularity
              if (popDiff !== 0) return popDiff
              // If same popularity, sort by distance
              return a.distance! - b.distance!
            })
        }
      } else {
        // Sort by popularity only
        places.sort((a, b) => b.popularity - a.popularity)
      }

      return NextResponse.json({ ok: true, places })
    }

    // Use curated famous destinations (updated popularity scores)
    const places = [...FAMOUS_DESTINATIONS]

    // Cache the results
    cache = { ts: Date.now(), data: places }

    // Apply filtering and sorting
    let filteredPlaces = places

    if (userLat && userLon && radius) {
      const lat = Number.parseFloat(userLat)
      const lon = Number.parseFloat(userLon)
      const radiusKm = Number.parseFloat(radius)

      if (!isNaN(lat) && !isNaN(lon) && !isNaN(radiusKm) && radiusKm > 0) {
        filteredPlaces = places
          .map((place) => ({
            ...place,
            distance: calculateDistance(lat, lon, place.lat, place.lon),
          }))
          .filter((place) => place.distance! <= radiusKm)
          .sort((a, b) => {
            // Higher popularity comes first
            const popDiff = b.popularity - a.popularity
            if (popDiff !== 0) return popDiff
            // If same popularity, sort by distance
            return a.distance! - b.distance!
          })
      }
    } else {
      filteredPlaces.sort((a, b) => b.popularity - a.popularity)
    }

    return NextResponse.json({ ok: true, places: filteredPlaces })
  } catch (error) {
    console.error("[wikidata-places] Error:", error)
    return NextResponse.json({ ok: false, error: "Failed to fetch places" }, { status: 500 })
  }
}
