"use client"

import { motion, useScroll, useTransform } from "framer-motion"
import Link from "next/link"
import { Compass, Map, Heart, Sparkles, ArrowRight, Globe, Users, TrendingUp } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useRef, useState } from "react"
import Image from "next/image"
import { useRouter } from "next/navigation"

const features = [
  {
    icon: Compass,
    title: "Swipe to Discover",
    description: "Browse through 500+ curated Indian destinations with our intuitive swipe interface",
  },
  {
    icon: Sparkles,
    title: "AI Itineraries",
    description: "Get personalized day-by-day trip plans generated by AI based on your preferences",
  },
  {
    icon: Heart,
    title: "Save Favorites",
    description: "Build your WanderList of dream destinations and share with friends",
  },
  {
    icon: Users,
    title: "Community",
    description: "Share your travel experiences and get inspired by other travelers",
  },
]

const stats = [
  { value: "500+", label: "Destinations", icon: Globe },
  { value: "10K+", label: "Travelers", icon: Users },
  { value: "50K+", label: "Itineraries", icon: TrendingUp },
]

export default function HomePage() {
  const heroRef = useRef<HTMLDivElement>(null)
  const router = useRouter()
  const [isFlying, setIsFlying] = useState(false)

  const { scrollYProgress } = useScroll({
    target: heroRef,
    offset: ["start start", "end start"],
  })

  const scale = useTransform(scrollYProgress, [0, 1], [1, 1.2])
  const opacity = useTransform(scrollYProgress, [0, 0.5], [1, 0])

  const handleExploreClick = () => {
    setIsFlying(true)
    setTimeout(() => {
      router.push("/explore")
    }, 3000)
  }

  const handleStartJourneyClick = () => {
    setIsFlying(true)
    setTimeout(() => {
      router.push("/onboarding")
    }, 3000)
  }

  return (
    <div className="min-h-screen">
      {isFlying && (
        <div className="fixed inset-0 z-[9999] bg-gradient-to-br from-sky-400 via-blue-500 to-indigo-600 flex items-center justify-center">
          <div className="relative w-full h-full overflow-hidden">
            <video
              autoPlay
              muted
              playsInline
              className="absolute inset-0 w-full h-full object-cover"
              src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Video%202025-12-13%20at%2010.26.46%20AM-4RkSYY23wgfFc9xwYT34u1m7pOQnoz.mp4"
            />

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.5 }}
              className="absolute inset-0 flex flex-col items-center justify-center gap-4 bg-black/20"
            >
              <motion.p
                animate={{ opacity: [0.5, 1, 0.5] }}
                transition={{ duration: 1.5, repeat: Number.POSITIVE_INFINITY }}
                className="text-3xl font-bold text-white drop-shadow-lg"
              >
                Taking off to explore...
              </motion.p>
            </motion.div>
          </div>
        </div>
      )}

      <section ref={heroRef} className="relative overflow-hidden h-screen">
        <motion.div style={{ scale }} className="absolute inset-0 w-full h-full">
          <Image
            src="/beautiful-indian-landscape-mountains-valleys-kashm.jpg"
            alt="Beautiful Indian landscape"
            fill
            className="object-cover"
            priority
            quality={100}
          />
          <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-background" />
        </motion.div>

        <motion.div
          style={{ opacity }}
          className="relative z-10 flex flex-col items-center justify-center h-full px-4 text-center"
        >
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 rounded-full border border-white/30 bg-white/10 backdrop-blur-md px-5 py-2 text-sm text-white mb-6"
          >
            <Sparkles className="h-4 w-4" />
            <span className="font-medium">AI-Powered Travel Planning</span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-5xl font-bold tracking-tight sm:text-6xl md:text-7xl lg:text-8xl text-balance max-w-5xl text-white drop-shadow-2xl"
          >
            Discover India's Hidden Gems
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mt-6 max-w-3xl text-xl text-white/90 md:text-2xl text-pretty drop-shadow-lg"
          >
            Swipe through stunning destinations, get AI-crafted itineraries, and plan your perfect Indian adventure in
            minutes.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="mt-10 flex flex-col gap-4 sm:flex-row"
          >
            <Button
              size="lg"
              className="gap-2 text-base px-8 h-14 bg-gradient-to-r from-primary to-secondary hover:from-primary/90 hover:to-secondary/90 text-white shadow-2xl pulse-glow"
              onClick={handleStartJourneyClick}
              disabled={isFlying}
            >
              <Map className="h-5 w-5" />
              Start Your Journey
              <ArrowRight className="h-5 w-5" />
            </Button>
            <Button
              size="lg"
              variant="outline"
              className="gap-2 text-base px-8 h-14 bg-white/10 backdrop-blur-md border-white/30 text-white hover:bg-white/20"
              onClick={handleExploreClick}
              disabled={isFlying}
            >
              <Compass className="h-5 w-5" />
              Explore Destinations
            </Button>
          </motion.div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1 }}
            className="absolute bottom-8 left-1/2 -translate-x-1/2"
          >
            <motion.div
              animate={{ y: [0, 10, 0] }}
              transition={{ duration: 2, repeat: Number.POSITIVE_INFINITY }}
              className="text-white/70 text-sm flex flex-col items-center gap-2"
            >
              <span>Scroll to explore</span>
              <svg
                width="20"
                height="20"
                viewBox="0 0 20 20"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M6 9l4 4 4-4" />
              </svg>
            </motion.div>
          </motion.div>
        </motion.div>
      </section>

      <section className="relative bg-background py-20 border-y border-border">
        <div className="mx-auto max-w-7xl px-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
            {stats.map((stat, index) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="text-center"
              >
                <div className="flex items-center justify-center gap-3 mb-4">
                  <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-primary/10 to-secondary/10">
                    <stat.icon className="h-7 w-7 text-primary" />
                  </div>
                </div>
                <div className="text-5xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
                  {stat.value}
                </div>
                <div className="mt-2 text-lg text-muted-foreground">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-24 bg-gradient-to-b from-background to-secondary/10">
        <div className="mx-auto max-w-7xl px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold md:text-5xl">Everything You Need to Travel Smart</h2>
            <p className="mt-4 text-xl text-muted-foreground max-w-2xl mx-auto">
              Plan, discover, and share your Indian adventures with powerful AI-driven features
            </p>
          </motion.div>

          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="group relative rounded-2xl border border-border bg-card p-8 card-hover"
              >
                <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-primary/10 to-secondary/10 group-hover:from-primary/20 group-hover:to-secondary/20 transition-colors mb-6">
                  <feature.icon className="h-8 w-8 text-primary" />
                </div>
                <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                <p className="text-muted-foreground leading-relaxed">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-24 bg-background">
        <div className="mx-auto max-w-7xl px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center"
          >
            <h2 className="text-3xl font-bold md:text-4xl mb-4">Loved by Travelers Across India</h2>
            <p className="text-xl text-muted-foreground mb-12 max-w-2xl mx-auto">
              Join thousands of adventurers discovering India's beauty
            </p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-16">
              {[
                {
                  quote: "WanderSwipe made planning my Ladakh trip so easy. The AI itinerary was spot-on!",
                  author: "Priya M.",
                  location: "Mumbai",
                },
                {
                  quote: "Discovered hidden gems in Rajasthan I never knew existed. Absolute game-changer!",
                  author: "Rahul K.",
                  location: "Delhi",
                },
                {
                  quote: "The swipe interface is addictive. Found my next 5 vacation spots in minutes!",
                  author: "Sneha P.",
                  location: "Bangalore",
                },
              ].map((testimonial, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className="rounded-2xl border border-border bg-card p-8 text-left"
                >
                  <p className="text-lg text-muted-foreground italic mb-6">"{testimonial.quote}"</p>
                  <div className="flex items-center gap-4">
                    <div className="h-12 w-12 rounded-full bg-gradient-to-br from-primary/20 to-secondary/20 flex items-center justify-center font-bold text-primary">
                      {testimonial.author.charAt(0)}
                    </div>
                    <div>
                      <div className="font-semibold">{testimonial.author}</div>
                      <div className="text-sm text-muted-foreground">{testimonial.location}</div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>

      <section className="py-24">
        <div className="mx-auto max-w-7xl px-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-primary via-primary to-secondary p-12 text-center md:p-20"
          >
            <div className="absolute inset-0 opacity-20">
              <div
                className="absolute inset-0"
                style={{
                  backgroundImage: 'url("/pattern-travel-icons-compass-map-globe.jpg")',
                  backgroundSize: "100px",
                  backgroundRepeat: "repeat",
                }}
              />
            </div>

            <div className="relative">
              <h2 className="text-4xl font-bold text-white md:text-5xl mb-6">Ready to Start Your Adventure?</h2>
              <p className="text-xl text-white/90 max-w-2xl mx-auto mb-10">
                Join thousands of travelers discovering incredible destinations across India with AI-powered planning.
              </p>
              <Link href="/onboarding">
                <Button
                  size="lg"
                  variant="secondary"
                  className="gap-2 text-base px-10 h-14 bg-white text-primary hover:bg-white/90 shadow-2xl font-semibold"
                >
                  Get Started Free
                  <ArrowRight className="h-5 w-5" />
                </Button>
              </Link>
              <p className="mt-6 text-sm text-white/70">No credit card required • Free forever</p>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  )
}
